#!/usr/bin/env bash
set -euo pipefail

export WE_T_PROJECT_NAME="$project_name" WE_T_PRIVATE_ROOT="$target_root"
export WE_T_PUBLIC_ROOT="$public_root" WE_T_WORKTREE_ROOT="$worktree_root"
export WE_T_WORKTREE_ROOT_REL="$worktree_root_rel"
export WE_T_PRIVATE_REMOTE_URL="$private_remote_url"
export WE_T_PUBLIC_REMOTE_URL="$public_remote_url"
export WE_T_PRIVATE_REPO_URL="$private_repo_url"
export WE_T_PUBLIC_REPO_URL="$public_repo_url"
export WE_T_PRIVATE_REPO_SLUG="$private_repo_slug"
export WE_T_PUBLIC_REPO_SLUG="$public_repo_slug"
export WE_T_PRIVATE_REPO_NAME="$private_repo_name"
export WE_T_PUBLIC_REPO_NAME="$public_repo_name"
export WE_T_PRIVATE_REMOTE_HINT="${private_repo_name}.git"
export WE_T_PUBLIC_REMOTE_HINT="${public_repo_name}.git"
export WE_T_PROJECT_TYPE="$project_type" WE_T_PACKAGE_NAME="$package_name"
export WE_T_CLI_BIN="$cli_bin"
export WE_T_CLI_ENTRY="${WE_SKILL_CLI_ENTRY:-${cli_entry:-from package.json}}"
export WE_T_LICENSE="${WE_SKILL_LICENSE:-${license:-UNSPECIFIED}}"
export WE_T_NPM_ACCESS="${WE_SKILL_NPM_ACCESS:-${npm_access:-public}}"
export WE_T_ARTIFACT_PREFIX="$artifact_prefix" WE_T_TARBALL_GLOB="$tarball_glob"
export WE_T_TARBALL_PATTERN="$tarball_pattern"
export WE_T_PUBLIC_KNOWLEDGE_DIR="$knowledge_dir"
export WE_T_EXPERIMENTAL_RUNTIME_PATH="$experimental_path"
export WE_T_SMOKE_COMMAND_1="$smoke_1" WE_T_SMOKE_COMMAND_2="$smoke_2"
export WE_T_SMOKE_COMMAND_3="$smoke_3"
export WE_T_RELEASE_STATUS="$release_status"
export WE_T_RELEASE_GUIDANCE="$release_guidance"
export WE_T_PUBLISH_STATUS="$publish_status"
export WE_T_PUBLISH_GUIDANCE="$publish_guidance"
