#!/usr/bin/env bash
set -euo pipefail

root="${1:-}"
if [[ -z "$root" || ! -d "$root" ]]; then
  echo "usage: render_placeholders.sh <directory>" >&2
  exit 2
fi

find "$root" -type f -print0 |
  while IFS= read -r -d '' file; do
    perl -0pi -e '
s/__WE_PROJECT_NAME__/$ENV{WE_T_PROJECT_NAME}/g;
s#__WE_PRIVATE_ROOT__#$ENV{WE_T_PRIVATE_ROOT}#g;
s#__WE_PUBLIC_ROOT__#$ENV{WE_T_PUBLIC_ROOT}#g;
s#__WE_WORKTREE_ROOT__#$ENV{WE_T_WORKTREE_ROOT}#g;
s#__WE_WORKTREE_ROOT_REL__#$ENV{WE_T_WORKTREE_ROOT_REL}#g;
s#__WE_PRIVATE_REMOTE_URL__#$ENV{WE_T_PRIVATE_REMOTE_URL}#g;
s#__WE_PUBLIC_REMOTE_URL__#$ENV{WE_T_PUBLIC_REMOTE_URL}#g;
s#__WE_PRIVATE_REPO_URL__#$ENV{WE_T_PRIVATE_REPO_URL}#g;
s#__WE_PUBLIC_REPO_URL__#$ENV{WE_T_PUBLIC_REPO_URL}#g;
s#__WE_PRIVATE_REPO_SLUG__#$ENV{WE_T_PRIVATE_REPO_SLUG}#g;
s#__WE_PUBLIC_REPO_SLUG__#$ENV{WE_T_PUBLIC_REPO_SLUG}#g;
s/__WE_PRIVATE_REPO_NAME__/$ENV{WE_T_PRIVATE_REPO_NAME}/g;
s/__WE_PUBLIC_REPO_NAME__/$ENV{WE_T_PUBLIC_REPO_NAME}/g;
s/__WE_PRIVATE_REMOTE_HINT__/$ENV{WE_T_PRIVATE_REMOTE_HINT}/g;
s/__WE_PUBLIC_REMOTE_HINT__/$ENV{WE_T_PUBLIC_REMOTE_HINT}/g;
s/__WE_PROJECT_TYPE__/$ENV{WE_T_PROJECT_TYPE}/g;
s/__WE_PACKAGE_NAME__/$ENV{WE_T_PACKAGE_NAME}/g;
s/__WE_CLI_BIN__/$ENV{WE_T_CLI_BIN}/g;
s/__WE_CLI_ENTRY__/$ENV{WE_T_CLI_ENTRY}/g;
s/__WE_LICENSE__/$ENV{WE_T_LICENSE}/g;
s/__WE_NPM_ACCESS__/$ENV{WE_T_NPM_ACCESS}/g;
s/__WE_ARTIFACT_NAME_PREFIX__/$ENV{WE_T_ARTIFACT_PREFIX}/g;
s/__WE_PACKAGE_TARBALL_GLOB__/$ENV{WE_T_TARBALL_GLOB}/g;
s/__WE_PACKAGE_TARBALL_PATTERN__/$ENV{WE_T_TARBALL_PATTERN}/g;
s#__WE_PUBLIC_KNOWLEDGE_DIR__#$ENV{WE_T_PUBLIC_KNOWLEDGE_DIR}#g;
s#__WE_EXPERIMENTAL_RUNTIME_PATH__#$ENV{WE_T_EXPERIMENTAL_RUNTIME_PATH}#g;
s/__WE_SMOKE_COMMAND_1__/$ENV{WE_T_SMOKE_COMMAND_1}/g;
s/__WE_SMOKE_COMMAND_2__/$ENV{WE_T_SMOKE_COMMAND_2}/g;
s/__WE_SMOKE_COMMAND_3__/$ENV{WE_T_SMOKE_COMMAND_3}/g;
s/__WE_RELEASE_ADAPTATION_STATUS__/$ENV{WE_T_RELEASE_STATUS}/g;
s/__WE_RELEASE_ADAPTATION_GUIDANCE__/$ENV{WE_T_RELEASE_GUIDANCE}/g;
s/__WE_PUBLISH_ADAPTATION_STATUS__/$ENV{WE_T_PUBLISH_STATUS}/g;
s/__WE_PUBLISH_ADAPTATION_GUIDANCE__/$ENV{WE_T_PUBLISH_GUIDANCE}/g;
' "$file"
  done
